### ISSUE TITLE
Gulp-sourcemaps support

### ISSUE THREAD

**Issue by zslabs** [gummesson/gulp-pixrem#4]
Any chance of adding in [gulp-sourcemaps](https://www.npmjs.org/package/gulp-sourcemaps) support? Would love to bundle this in. Thanks!

**Comment by noxoc** [comment]
+1,

Is there any update on this? Or are there alternatives you could point me to?

**Comment by gummesson** [comment]
Sorry, I totally forgot!

I'm working on it right now, it should be up later today or tomorrow. :)

**Comment by gummesson** [comment]
I just published a new version. Can anyone confirm that it works okay?
