### ISSUE TITLE
Update docs to include atrules option

### ISSUE THREAD

**Issue by ryandrewjohnson** [gummesson/gulp-pixrem#7]
The README currently does not include information on the `atrules` option that is available. The default settings set `atrules: false`, which means any CSS in media queries will be ignored. I only found out about this option after noticing that my media queries were being ignored and going through the source. 

This was a quick fix once I found the option, but this should be in the docs to help out the next guy.

**Comment by gummesson** [comment]
Thanks for the suggestion!

I added a small note on [usage](https://github.com/gummesson/gulp-pixrem#usage) which refers to the official repository (since this is just a simple "wrapper" plugin).
